### ISSUE TITLE
Faction Creation

### ISSUE THREAD

**Issue by BobTheGimp** [B-iggy/HWS-Plus-Creative-Scenario#2]
Are you able to allow player faction creation in the test environment so that faction PvP can be tested easily. While the command line Faction operations work, they are clunky and make it harder to use factions.
Cheers
Michael

**Comment by B-iggy** [comment]
What do you mean by that exactly?
I can only add NPC factions, not dummy player factions though.
You can spawn your own ships though and set it to your desired faction to fight against them?

**Comment by BobTheGimp** [comment]
I am not sure how the faction config is setup in the config files, but in the normal game you can open the Faction menu and you have the option to Create, Join, alliance etc in the different Origins. In the this scenario when you go to the Faction menu you are only presented with the list of  NPC Factions with no option for player factions. The only local changes I have made is to add -Creative to the top section of the YAML and -Freedom to the bottom section. We are using the test server in Freedom mode as it allows creative style building tools etc.
![HWSPlus_2022-06-16_21-03-04](https://user-images.githubusercontent.com/76391116/174056649-1e4de9b3-c0ea-4fe5-88f2-0b777d9dffe4.png)

**Comment by B-iggy** [comment]
AH, thanks, got you now. Origins is what you meant in its core.
Right, those are set in the Universe but since this test scenario has no real universe, I've set it to one or well, one start planet.
I could make an exact clone of Homeworld with a different Origin, yes.

**Comment by B-iggy** [comment]
Ok, so you have 2 Origins now. That is what you wanted, right?
https://github.com/B-iggy/HWS-Plus-Creative-Scenario/commit/4eed2ddd35a5819ed08821f477ba098564fb4184
![image](https://user-images.githubusercontent.com/7815434/174071000-9f55c150-892b-49b9-a94a-a159cfb744af.png)

Rethinking it... it's rather a bug that you had only NPC in the first place. I think because of Freedom mode or other settings you changed...
