### ISSUE TITLE
Wipe structures and taxes on ECC?!

### ISSUE THREAD

**Issue by AgentMasters** [B-iggy/HWS-Plus-Creative-Scenario#20]
I build my base on ECC planet and after wipe on RE EU do not play some time. Now after login i see that my base was wiped and in connect website see that i have been taxed for that?!? WTF if ECC was in list of starter planets?! How i can test the bugs without my resources?!

**Comment by AgentMasters** [comment]
Rex, why you taxed your beta testers on the starter placet ECC?! Now im taxed for  2 CV  but they have one ID ??? 
![image](https://user-images.githubusercontent.com/107882107/179690844-ee6a2ae7-087d-4461-88d6-026511f3ba55.png)

**Comment by B-iggy** [comment]
> I build my base on ECC planet
Ho? How did you do this? This should not be possible at all and never was possible.
ECC is set to starter planet because of Dealer Origin. Doesn't mean you can build bases there. It's a special start.
Taxes on ECC is also correct. Again, ECC Start is not for new players or settlers. (as written in the description on first join)

**Comment by AgentMasters** [comment]
I build the second base - but that is not important - i need to get back my resources - then i will remove it! Please return it back just for a day
